### ISSUE TITLE
Add SteamOS Btrfs

### ISSUE THREAD

**Issue by HugLifeTiZ** [airscripts/awesome-steam-deck#30]
**Is your feature request related to a problem? Please describe.**
No problem.

**Describe the solution you'd like**
Add SteamOS Btrfs to the Software section: https://gitlab.com/popsulfr/steamos-btrfs

**Describe alternatives you've considered**
I don't believe any alternatives are available to provide btrfs support for `/home` and SD cards on SteamOS.

**Additional context**
This project will convert the `/home` partition in SteamOS to the btrfs filesystem, and allow SD cards to use that filesystem as well. This has several benefits, like the potential for space savings via transparent compression and deduplication, as well as the use of subvolumes and snapshots for more technical applications. The project also provides an optional weekly deduplication service that is particularly helpful for compatdata.

It is not without drawbacks, though: btrfs does not support casefolding like ext4 does, so Proton and Wine have to use the slower fallback codepath, which could hypothetically impact applications that make frequent filesystem accesses. I haven't run into any games that do that yet.

**Comment by HugLifeTiZ** [comment]
As an aside, I'm not sure the existing issue templates are well suited to this project.

**Comment by airscripts** [comment]
> As an aside, I'm not sure the existing issue templates are well suited to this project.

Do you think a simpler template will be more suitable?

**Comment by airscripts** [comment]
Accidentally closed after merging the PR, sorry!

**Comment by HugLifeTiZ** [comment]
> Do you think a simpler template will be more suitable?

Yeah. The templates concern "bugs", "feature requests", and "security vulnerabilities", which are not applicable to this sort of repo. This repo should basically only concern itself with additions to the list, and removals/replacements from the list.

You basically just need two questions for an addition: "What do you want to add, and in what section?" and "What benefit does it provide Steam Deck users?"

You may want a separate template for a removal/replacement: "What do you want to remove or replace, and from what section?" and "What happened to the project that necessitates its removal or replacement?"

**Comment by airscripts** [comment]
You're totally right. Usually I use a predefined template for all my repositories.  
I'll be making the changes you suggested soon.  
Thank you kindly for your precious support @HugLifeTiZ. I really appreciate that!
