### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by Droppisalt** [airscripts/awesome-steam-deck#39]
This link doesn't exist anymore: [Install NonSteamLaunchers](https://www.steamdeckgaming.net/post/easy-launchers-install-on-steam-deck)

Could be switched to this one: https://steamdeckhq.com/tips-and-guides/install-3rd-party-launchers-on-steam-deck/

**Comment by airscripts** [comment]
Hey there, @Droppisalt! Sorry for keeping you waiting, I've got a busy weekend!
Thank you kindly for reaching me out, I'll be opening a pull request right now with your deeply appreciated change.
