### ISSUE TITLE
Add MagicPods for Steam Deck plugin

### ISSUE THREAD

**Issue by steam3d** [airscripts/awesome-steam-deck#42]
**Is your feature request related to a problem? Please describe.**
No Problem

**Describe the solution you'd like**
Add MagicPods for Steam Deck to the Plugin section: https://github.com/airscripts/awesome-steam-deck?tab=readme-ov-file#plugin

**Describe alternatives you've considered**
No alternatives

**Additional context**
Plugin allow controlling AirPods and Beats headphones. Switch noise cancellations modes, display accurate battery etc.
https://magicpods.app/steamdeck/
![screenshot-1](https://github.com/airscripts/awesome-steam-deck/assets/30986874/238db9ec-11ba-4126-8654-727bfa776c95)

**Comment by airscripts** [comment]
Thank you kindly for your contribution, I've added this fantastic plugin to the list in #43.
