### ISSUE TITLE
Add greenlight

### ISSUE THREAD

**Issue by jdsuhlmann** [airscripts/awesome-steam-deck#44]
Please add greenlight, because there is a link to an app for PS4/PS5 streaming, but no app to do that for xbox
Here is the link to the greenlight GitHub:
[https://github.com/unknownskl/greenlight](url)

**Comment by airscripts** [comment]
Hey there @jdsuhlmann!  
Thank you kindly for your contribution, I've added `greenlight` to the list.  
More details into #45.
